SELECT EntityID, SUBSTRING(CAST(RawEDIFile AS VARCHAR(max)),CHARINDEX('B10*',CAST(RawEDIFile AS VARCHAR(max)),0)+4,6) AS 'shipmentID', 
SUBSTRING(CAST(RawEDIFile AS VARCHAR(max)),CHARINDEX('AT7*',CAST(RawEDIFile AS VARCHAR(max)),0)+4,25) AS 'DateTime', 
* FROM dbo.EDIInOutbound WITH (NOLOCK)
WHERE EntityID = 763754
